server.servlet.session:
  timeout: 5m

# -------------------------------------------------------------------------------------------------
# Logging properties
# -------------------------------------------------------------------------------------------------
logging:
  level:
    ROOT: info